openapi: 3.0.0
info:
  title: Learn express and swagger -LearnCodeOnline
  description: LCO - a course segment about writing docs
  version: 1.1.0
  contact:
    email: sp647600@gmail.com
    url: "https://saurabh-pande.netlify.com"

# servers:
#   - url: "https://localhost:8000/api/v1"
#     description: for local host -secure
#   - url: "http://localhost:8000/api/v1"
#     description: for local host -regular

servers:
  - url: "{protocol}://localhost:8000/api/{version}"
    description: for local host -secure
    variables:
      version:
        enum: 
          - v1
          - v2
        default: v1 
      protocol:
        enum:
          - http
          - https
        default: http
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token          
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /lco:
    get:
      tags:
        - String
      summary: return a greet message from LCO
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:
          description: internal server error
  /lcoobject:
    get:
      tags:
        - Object
      summary: return a unique course from LCO
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: number

        400:
          description: Bad request
        500:
          description: internal server error






